---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: demo-onlinestore-ui
- name: current-app-info

run:
  path: demo-onlinestore-ui/ci/tasks/bg-upgrade.sh
