---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"


inputs:
- name: demo-onlinestore-ui
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: demo-onlinestore-ui/ci/tasks/edit-manifest.sh