---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine    
inputs:
  - name: demo-onlinestore-ui

run:
  path: demo-onlinestore-ui/ci/tasks/unit.sh